#spring.application.name=text-extractor
spring:
  application:
    name: TextExtractor
  # datasource:
  #   url: jdbc:h2:mem:test
  #   username: sa
  #   password:
  #   driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: received-documents
application:
  uploadpath: src/main/resources/upload
  image:
    extensions:
    - png
    - jpg
    - gif
    - bmp
tesseract:
  datapath: src/main/resources/tessdata
  language: eng+rus
  pagemode: 1
  enginemode: 2